// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU836fqSI3jyZKDrNghMnZTsFETpD3g-I',
    appId: '1:37742433346:web:2ed33c13f3d7aee02dc9db',
    messagingSenderId: '37742433346',
    projectId: 'fincontrol-549fc',
    authDomain: 'fincontrol-549fc.firebaseapp.com',
    storageBucket: 'fincontrol-549fc.firebasestorage.app',
    measurementId: 'G-RW507NTXLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40icGsaCWFywqw5s9LCUNrqVB0hAaU0Q',
    appId: '1:37742433346:android:a1d60b58f37b32df2dc9db',
    messagingSenderId: '37742433346',
    projectId: 'fincontrol-549fc',
    storageBucket: 'fincontrol-549fc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2He-Od3X4jwIBb8GR-aYuvlNdn140tU',
    appId: '1:37742433346:ios:2c1d0dfe102c6ce82dc9db',
    messagingSenderId: '37742433346',
    projectId: 'fincontrol-549fc',
    storageBucket: 'fincontrol-549fc.firebasestorage.app',
    iosBundleId: 'com.finatech.fincontrol',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2He-Od3X4jwIBb8GR-aYuvlNdn140tU',
    appId: '1:37742433346:ios:2c1d0dfe102c6ce82dc9db',
    messagingSenderId: '37742433346',
    projectId: 'fincontrol-549fc',
    storageBucket: 'fincontrol-549fc.firebasestorage.app',
    iosBundleId: 'com.finatech.fincontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU836fqSI3jyZKDrNghMnZTsFETpD3g-I',
    appId: '1:37742433346:web:7d05a62fc0362d422dc9db',
    messagingSenderId: '37742433346',
    projectId: 'fincontrol-549fc',
    authDomain: 'fincontrol-549fc.firebaseapp.com',
    storageBucket: 'fincontrol-549fc.firebasestorage.app',
    measurementId: 'G-39JT2BFNJE',
  );
}
